### ISSUE TITLE
Conflict with spell checkers

### ISSUE THREAD

**Issue by Lobojpm** [jtjoo/vscode-classic-asp-extension#4]
Hello!  Thanks for writing this- it definitely helps with editing and refactoring older Classic ASP code.

On issue I noticed is that it seems to conflict with all of the Spell Checking extensions that I try.  The one I like the best is called "Spell Right" (https://github.com/bartosz-antosik/vscode-spellright)

This extension works great to show spelling errors, but when I enable this Classic ASP extension, the spell checker doesn't flag any words as misspelled.  

Anything hints you might have are much appreciated.  Thanks.

**Comment by jtjoo** [comment]
I checked the problem, I will find what's wrong with it.
Temporal solution is set the syntax to Visual Basic. 
It will help check misspelled words on your ASP code.

Sorry for late answer, thanks!

**Comment by jtjoo** [comment]
Hi, I released snippet added version right now.
Unfortunately, I couldn't fix your problem yet...
Sorry for that, but I am trying to found out solution and I'll find out what is wrong.

It is hard to fix extension's conflict problem because there is no documents or similar issues via communities like StackOverFlow.
These days I'm analyzing other extensions and VSCode's sources to find out problem.
I am thinking about open an issue on VSCode's repository.

Hope new snippet helps.
Thanks!

**Comment by jtjoo** [comment]
After "Spell Right" updated, now it seems to work correctly. So I close this case. If you find additional problem or question, open this case again or contact me. Feedbacks are always welcome!

**Comment by lvjunxi** [comment]
i am using 'auto close tag' and 'auto reman tage'
add 
    "auto-close-tag.activationOnLanguage": ["*"],
    "auto-rename-tag.activationOnLanguage": ["*"]
at settings.json

**Comment by lvjunxi** [comment]
i am using 'auto close tag' and 'auto rename tage'
add
"auto-close-tag.activationOnLanguage": [""],
"auto-rename-tag.activationOnLanguage": [""]
at settings.json
